import React from "react";

export default function Modale() {
	return (
		<div>
			<div className="head">
				<title>Modale</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</div>
			<Modale />
		</div>
	);
}
